# NOVA BROWSER TEST SCRIPT
# Run this to test each module in the browser

Write-Host "=========================================="
Write-Host "NOVA BROWSER TEST"
Write-Host "=========================================="
Write-Host ""
Write-Host "Instructions:"
Write-Host "1. Open http://localhost:3000 in your browser"
Write-Host "2. Navigate to each page using the sidebar"
Write-Host "3. Test the functionality described below"
Write-Host "4. Check browser console for errors"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 1: NOVA PAGE (/nova)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/nova"
Write-Host "2. Type a message in the chat input"
Write-Host "3. Click Send or press Enter"
Write-Host "4. Verify you get an LLM response (not keyword-matched)"
Write-Host "5. Refresh the page"
Write-Host "6. Verify chat history is still visible"
Write-Host "7. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Chat works, history persists across refresh"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 2: PROJECTS PAGE (/projects)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/projects"
Write-Host "2. Verify projects list loads (should show existing projects)"
Write-Host "3. Click 'Create Project' button"
Write-Host "4. Fill in name and description"
Write-Host "5. Click 'Create'"
Write-Host "6. Verify new project appears in list"
Write-Host "7. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Projects load, creation works"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 3: GOALS PAGE (/goals)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/goals"
Write-Host "2. Verify goals list loads (should not show 404)"
Write-Host "3. Click 'Create Goal' button"
Write-Host "4. Fill in title and description"
Write-Host "5. Select priority"
Write-Host "6. Click 'Save Goal'"
Write-Host "7. Verify new goal appears in list"
Write-Host "8. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Goals load without 404, creation works"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 4: TASKS PAGE (/tasks)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/tasks"
Write-Host "2. Verify tasks list loads"
Write-Host "3. Check if 'Create Task' button exists"
Write-Host "4. If it exists, try creating a task"
Write-Host "5. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Tasks load, creation works (if button exists)"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 5: ROADMAPS PAGE (/roadmaps)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/roadmaps"
Write-Host "2. Verify roadmaps list loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Roadmaps load"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 6: BACKLOG PAGE (/backlog)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/backlog"
Write-Host "2. Verify backlog list loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Backlog loads"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 7: APPROVALS PAGE (/approvals)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/approvals"
Write-Host "2. Verify approvals list loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Approvals load"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 8: CHAT PAGE (/chat)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/chat"
Write-Host "2. Type a message in the chat input"
Write-Host "3. Click Send or press Enter"
Write-Host "4. Verify you get an LLM response"
Write-Host "5. Refresh the page"
Write-Host "6. Verify chat history is still visible"
Write-Host "7. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Chat works, history persists across refresh"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 9: MEMORY PAGE (/memory)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/memory"
Write-Host "2. Verify memory status loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Memory status loads"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 10: OBSERVABILITY PAGE (/observability)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/observability"
Write-Host "2. Verify observability data loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Observability data loads"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 11: TOOLS PAGE (/tools)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/tools"
Write-Host "2. Verify tools list loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Tools load"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 12: WORKFLOWS PAGE (/workflows)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/workflows"
Write-Host "2. Verify workflows list loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Workflows load"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 13: DASHBOARD PAGE (/dashboard)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/dashboard"
Write-Host "2. Verify dashboard loads"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Dashboard loads"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 14: SETTINGS PAGE (/settings)"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/settings"
Write-Host "2. Verify settings load"
Write-Host "3. Check browser console for errors"
Write-Host ""
Write-Host "Expected: Settings load"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 15: SESSION PERSISTENCE"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/nova"
Write-Host "2. Send a message in chat"
Write-Host "3. Navigate to /projects"
Write-Host "4. Navigate back to /nova"
Write-Host "5. Verify chat history is still visible"
Write-Host "6. Refresh the page"
Write-Host "7. Verify chat history is still visible"
Write-Host ""
Write-Host "Expected: Session persists across navigation and refresh"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST 16: USER ID CONSISTENCY"
Write-Host "=========================================="
Write-Host "1. Open http://localhost:3000/goals"
Write-Host "2. Create a goal"
Write-Host "3. Open browser DevTools > Application > Local Storage"
Write-Host "4. Check if 'nova-app-store' exists with userId"
Write-Host "5. Navigate to other pages that use userId"
Write-Host "6. Verify they all use the same userId"
Write-Host ""
Write-Host "Expected: All pages use the same userId from store"
Write-Host "Actual: [ ] PASS [ ] FAIL"
Write-Host ""

Write-Host "=========================================="
Write-Host "TEST COMPLETE"
Write-Host "=========================================="
Write-Host ""
Write-Host "Fill in the results above and report back."
Write-Host "For any FAIL, note the specific error or issue."
Write-Host "=========================================="
