apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nova-data-pvc
  labels:
    app: nova-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nova-postgres-pvc
  labels:
    app: nova-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
