"""RAG & Retrieval module — retrieval-augmented generation for NOVA CORE."""

from app.rag.base import (
    CitationProvider,
    ContextBuilder,
    EmbeddingProvider,
    QueryRewriter,
    Reranker,
    Retriever,
    VectorRepository,
)
from app.rag.citations import DefaultCitationProvider, EnhancedCitationProvider, get_citation_provider
from app.rag.context_builder import CompactContextBuilder, DefaultContextBuilder, get_context_builder
from app.rag.embeddings import (
    InMemoryEmbeddingProvider,
    OllamaEmbeddingProvider,
    OpenAIEmbeddingProvider,
    GoogleEmbeddingProvider,
    get_embedding_provider,
)
from app.rag.engine import RAGEngine
from app.rag.factory import RAGFactory, get_rag_factory
from app.rag.filters import (
    apply_filters,
    build_category_filter,
    build_source_filter,
    build_tag_filter,
    merge_filters,
)
from app.rag.index import RAGIndex
from app.rag.lifecycle import RAGLifecycle, RAGLifecycleError, RAGState
from app.rag.metrics import RAGMetrics, RequestMetric, get_rag_metrics
from app.rag.pipeline import RAGPipeline
from app.rag.query_rewriter import (
    ContextualRewriter,
    HyDEQueryRewriter,
    KeywordExpansionRewriter,
    PassthroughRewriter,
    get_query_rewriter,
)
from app.rag.reranker import (
    CrossEncoderReranker,
    HybridScoreReranker,
    ImportanceAwareReranker,
    RecencyAwareReranker,
    SimilarityReranker,
    get_reranker,
)
from app.rag.repository import ChromaRepository, InMemoryRepository, get_repository
from app.rag.retriever import (
    HybridRetriever,
    KeywordRetriever,
    KnowledgeRetriever,
    MemoryRetriever,
    VectorRetriever,
    get_retriever,
)
from app.rag.schemas import (
    Chunk,
    ChunkMetadata,
    ChunkStrategy,
    Citation,
    ContextPackage,
    DocumentStatus,
    FilterCondition,
    FilterOperator,
    IndexDocument,
    IndexResult,
    QueryRewrite,
    RetrievedChunk,
    RetrievalMethod,
    RetrievalQuery,
    RetrievalResult,
    RetrievalStatus,
)
from app.rag.tracing import RAGTracer, RAGTrace, RAGSpan, get_rag_tracer

__all__ = [
    "RAGEngine",
    "RAGFactory",
    "RAGIndex",
    "RAGLifecycle",
    "RAGLifecycleError",
    "RAGState",
    "RAGMetrics",
    "RAGPipeline",
    "RAGTracer",
    "RAGTrace",
    "RAGSpan",
    "RequestMetric",
    "Retriever",
    "Reranker",
    "Chunker",
    "EmbeddingProvider",
    "QueryRewriter",
    "ContextBuilder",
    "CitationProvider",
    "VectorRepository",
    "VectorRetriever",
    "KeywordRetriever",
    "HybridRetriever",
    "MemoryRetriever",
    "KnowledgeRetriever",
    "SimilarityReranker",
    "CrossEncoderReranker",
    "HybridScoreReranker",
    "RecencyAwareReranker",
    "ImportanceAwareReranker",
    "InMemoryEmbeddingProvider",
    "OllamaEmbeddingProvider",
    "OpenAIEmbeddingProvider",
    "GoogleEmbeddingProvider",
    "InMemoryRepository",
    "ChromaRepository",
    "DefaultContextBuilder",
    "CompactContextBuilder",
    "DefaultCitationProvider",
    "EnhancedCitationProvider",
    "PassthroughRewriter",
    "KeywordExpansionRewriter",
    "ContextualRewriter",
    "HyDEQueryRewriter",
    "Chunk",
    "ChunkMetadata",
    "ChunkStrategy",
    "Citation",
    "ContextPackage",
    "DocumentStatus",
    "FilterCondition",
    "FilterOperator",
    "IndexDocument",
    "IndexResult",
    "QueryRewrite",
    "RetrievedChunk",
    "RetrievalMethod",
    "RetrievalQuery",
    "RetrievalResult",
    "RetrievalStatus",
    "get_rag_factory",
    "get_rag_metrics",
    "get_rag_tracer",
    "get_embedding_provider",
    "get_repository",
    "get_retriever",
    "get_reranker",
    "get_query_rewriter",
    "get_context_builder",
    "get_citation_provider",
    "apply_filters",
    "build_tag_filter",
    "build_source_filter",
    "build_category_filter",
    "merge_filters",
]
