abstract class LocalizationService {
  String get appTitle;
  String get dashboard;
  String get chat;
  String get agents;
  String get workflows;
  String get goals;
  String get tasks;
  String get memory;
  String get rag;
  String get models;
  String get tools;
  String get plugins;
  String get scheduler;
  String get events;
  String get observability;
  String get deployment;
  String get scaling;
  String get security;
  String get enterprise;
  String get settings;
  String get admin;
  String get system;
  String get login;
  String get logout;
  String get search;
  String get loading;
  String get error;
  String get retry;
  String get noData;
  String get send;
  String get connect;
  String get disconnect;
}

class EnglishLocalization implements LocalizationService {
  @override String get appTitle => 'NOVA CORE';
  @override String get dashboard => 'Dashboard';
  @override String get chat => 'Chat';
  @override String get agents => 'Agents';
  @override String get workflows => 'Workflows';
  @override String get goals => 'Goals';
  @override String get tasks => 'Tasks';
  @override String get memory => 'Memory';
  @override String get rag => 'RAG';
  @override String get models => 'Models';
  @override String get tools => 'Tools';
  @override String get plugins => 'Plugins';
  @override String get scheduler => 'Scheduler';
  @override String get events => 'Events';
  @override String get observability => 'Observability';
  @override String get deployment => 'Deployment';
  @override String get scaling => 'Scaling';
  @override String get security => 'Security';
  @override String get enterprise => 'Enterprise';
  @override String get settings => 'Settings';
  @override String get admin => 'Admin';
  @override String get system => 'System';
  @override String get login => 'Login';
  @override String get logout => 'Logout';
  @override String get search => 'Search';
  @override String get loading => 'Loading...';
  @override String get error => 'Error';
  @override String get retry => 'Retry';
  @override String get noData => 'No data available';
  @override String get send => 'Send';
  @override String get connect => 'Connect';
  @override String get disconnect => 'Disconnect';
}
